### ISSUE TITLE
ThreadDisplay.jsx:9 Uncaught TypeError: _this.props.database.ref is not a function

### ISSUE THREAD

**Issue by kolmstead** [zacbraddy/AppInAnHour_FinalForum#1]
I was getting this error in console: ThreadDisplay.jsx:9 Uncaught TypeError: _this.props.database.ref is not a function

I had to change line 9 of ThreadDisplay.jsx from `this.props.database.ref().child...` to
`this.props.database().ref().child...`   so `database().ref` instead of `database.ref`

Not sure why -- your code on screen and here in repo doesn't have it. But that cleared the error I was getting.

Enjoyed your tutorial. Thanks.

**Comment by zacbraddy** [comment]
Hi @kolmstead 

Thanks for reporting your error and for the kind words about my tutorial. It seems odd that I wasn't getting this error in the tutorial video itself. What you find in this repo is exactly the code that I developed during the tutorial, almost completely untouched.

Tell me, in your code have you perhaps forgotten the parentheses on this this line in App.js?

https://github.com/zacbraddy/AppInAnHour_FinalForum/blob/master/src/App.js#L17

If not then then I would suggest, forking this repo and pulling the code down to your machine. Then you can copy your code over the top of your fork and look at the git diff to see where your code and mine differ, this might help to identify the problem further.

Cheers
Zac

**Comment by kolmstead** [comment]
That was close to the issue I was having. On line 22 I had 
   `<ThreadDisplay database={this.app.database} />` 
instead of 
   ` <ThreadDisplay database={this.database} />` in the component. 
Thanks for the help.
